#!/home/s/ops/perl/bin/perl
use strict;
use warnings;

use Dancer;
use YAML::XS;
use File::Basename;
use NS::Util::OptConf;
set serializer => 'YAML';

use Data::Dumper;

$| ++;

my %opt;
BEGIN{ %opt = NS::Util::OptConf->load()->dump('apps'); };

my $REGX = '^[\@A-Za-z0-9-_\.]+$';

get "/apps" => sub
{
    my %param = %{request->params};
    for( qw( apps node pack ) )
    {
        next unless my $s = $param{$_};
        return "$_ syntax err" unless $s =~ /$REGX/;
        if ( -f "$opt{data}/$_" )
        {
            my $a =  eval{ YAML::XS::LoadFile "$opt{data}/$_" };
            return ( $a && ref $a eq 'HASH' ) ? $a->{$s} : '';
        }
        else
        {
            return eval{ YAML::XS::LoadFile "$opt{data}/$_/$s" };
        }
    }
};

dance;
